[BT-5174-http-timeout] Allow user-configurable HTTP timeout for query and stream requests.
fauna/fauna-jvm pull request #153
Opened 2024-10-10 00:14 UTC by findgriffin

### Description
I added support for setting the HttpClient timeout (HttpClient connect timeout, and Fauna query are already configurable).

### Motivation and context

I noticed this when testing logging support on Monday. It seems minor, but could also be frustrating for customers if we don't support it.

### How was the change tested?

Unit and E2E tests.

### Screenshots (if appropriate):

### Change types

* - [x] Bug fix (non-breaking change that fixes an issue)
* - [ ] New feature (non-breaking change that adds functionality)
* - [ ] Breaking change (backwards-incompatible fix or feature)

### Checklist:

* - [x] My code follows the code style of this project.
* - [ ] My change requires a change to Fauna documentation.
* - [ ] My change requires a change to the README, and I have updated it accordingly.

----
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-10-10 10:10 UTC, pnwpedro requested changes

2024-10-10 10:10 UTC, pnwpedro commented on src/main/java/com/fauna/stream/StreamRequest.java
> +         * Therefore, it's a timeout on the stream being opened, but the stream can stay open indefinitely.
What's the default, and if the default is null what does that mean? We should describe that clearly.

Also, to me, a query timeout and stream open timeout are essentially the same thing. Maybe we should use the same defaults if we're not already.

2024-10-15 22:33 UTC, jdcryans commented on src/main/java/com/fauna/client/RequestBuilder.java
> +    private static final int TIMEOUT_BUFFER_MS = 1000;
I would suggest aligning with js here, AFAIK quite a bit of thought was given to those defaults there https://github.com/fauna/fauna-js?tab=readme-ov-file#client-timeout

2024-10-16 20:56 UTC, jdcryans reviewed
Could also add to the README

2024-10-16 20:56 UTC, jdcryans commented on src/main/java/com/fauna/client/FaunaConfig.java
> +     *
Forgot a commit?

2024-10-16 20:56 UTC, jdcryans commented on src/main/java/com/fauna/client/RequestBuilder.java
> +
Could delete this line.

2024-10-21 21:41 UTC, jdcryans approved these changes

2024-10-21 21:51 UTC, merged